# _config.yml

theme: jekyll-theme-minimal

#Configuration variables

#Minimal will respect the following variables, if set in your site's _config.yml:

#title: [The title of your site]
#description: [A short description of your site's purpose]

#Additionally, you may choose to set the following optional variables:

#show_downloads: ["true" or "false" (unquoted) to indicate whether to provide a download URL]
#google_analytics: [Your Google Analytics tracking ID]

title: alana's traumarama
description: you can read about a trans woman's anguish. You know, if you're into that kind of thing.
